; Exercise 1.9.  Each of the following two procedures defines a method for
; adding two positive integers in terms of the procedures inc, which increments
; its argument by 1, and dec, which decrements its argument by 1.

(define (+ a b)
  (if (= a 0)
      b
      (inc (+ (dec a) b))))

; (inc (+ (dec 4) 5))
; (inc (+ 3 5))
;     (inc (+ (dec 3) 5))
;     (inc (+ 2 5))
;         (inc (+ (dec 2) 5))
;         (inc (+ 1 5))
;             (inc (+ (dec 1) 5))
;             (inc (+ 0 5))
;             (inc 5)
;             6
;         (inc 6)
;         7
;     (inc 7)
;     8
; (inc 8)
; 9

(define (+ a b)
  (if (= a 0)
      b
      (+ (dec a) (inc b))))

; (+ 4 5)
; (+ (dec 4) (inc 5))
; (+ 3 6)
; (+ (dec 3) (inc 6))
; (+ 2 7)
; (+ (dec 2) (inc 7))
; (+ 1 8)
; (+ (dec 1) (inc 8))
; (+ 0 9)
; 9

; Using the substitution model, illustrate the process generated by each
; procedure in evaluating (+ 4 5). Are these processes iterative or recursive?
; The first process is iterative, the second is recursive.
